"""chenges

Revision ID: 23e56fcb337b
Revises: 5db383793464
Create Date: 2022-02-27 07:03:06.041336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23e56fcb337b'
down_revision = '5db383793464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_code', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('water', sa.Boolean(), nullable=True),
    sa.Column('lather', sa.Boolean(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_code')
    )
    op.drop_table('qr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('img_path', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('device_content')
    # ### end Alembic commands ###
