"""Asdvs

Revision ID: 2ba3b6ef1135
Revises: 228ca52b14d4
Create Date: 2022-04-20 13:40:13.940093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba3b6ef1135'
down_revision = '228ca52b14d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('car_wash_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'car_wash_id')
    # ### end Alembic commands ###
