"""asdasdad

Revision ID: 326095536168
Revises: 459726dd754c
Create Date: 2022-03-16 12:10:17.068520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326095536168'
down_revision = '459726dd754c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyal_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loyal_card')
    # ### end Alembic commands ###
