"""changes

Revision ID: 3e6856890a1d
Revises: bce614abc4f8
Create Date: 2022-02-17 18:23:19.315545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e6856890a1d'
down_revision = 'bce614abc4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_column('device', 'car_wash_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('car_wash_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('device', 'owner_id')
    # ### end Alembic commands ###
