"""chenges

Revision ID: 44e0ce4cbf15
Revises: 67388f1de656
Create Date: 2022-02-27 14:35:23.287734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44e0ce4cbf15'
down_revision = '67388f1de656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_content')
    op.add_column('device', sa.Column('water', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('lather', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'lather')
    op.drop_column('device', 'water')
    op.create_table('device_content',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('water', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('lather', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_update', mysql.DATETIME(), nullable=True),
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
