"""sv

Revision ID: 50c58ed8d649
Revises: fc1aeede2748
Create Date: 2022-04-23 09:50:39.142621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50c58ed8d649'
down_revision = 'fc1aeede2748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='car_wash')
    op.drop_index('username', table_name='car_wash')
    op.drop_column('car_wash', 'password')
    op.drop_column('car_wash', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_wash', sa.Column('username', mysql.VARCHAR(length=60), nullable=False))
    op.add_column('car_wash', sa.Column('password', mysql.VARCHAR(length=180), nullable=False))
    op.create_index('username', 'car_wash', ['username'], unique=False)
    op.create_index('password', 'car_wash', ['password'], unique=False)
    # ### end Alembic commands ###
