"""chenge

Revision ID: 5db383793464
Revises: b2594023f09b
Create Date: 2022-02-19 17:05:16.331773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5db383793464'
down_revision = 'b2594023f09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_payment', 'device_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_payment', sa.Column('device_code', mysql.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
