"""asd

Revision ID: 67388f1de656
Revises: 23e56fcb337b
Create Date: 2022-02-27 13:26:35.327067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67388f1de656'
down_revision = '23e56fcb337b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_content', sa.Column('device_id', sa.Integer(), nullable=False))
    op.drop_index('device_code', table_name='device_content')
    op.drop_column('device_content', 'owner_id')
    op.drop_column('device_content', 'device_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_content', sa.Column('device_code', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('device_content', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('device_code', 'device_content', ['device_code'], unique=False)
    op.drop_column('device_content', 'device_id')
    # ### end Alembic commands ###
