"""chenges

Revision ID: 6ef1fd61de46
Revises: 970aaf16a45f
Create Date: 2022-02-19 07:33:54.722193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef1fd61de46'
down_revision = '970aaf16a45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_payment', sa.Column('owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_payment', 'owner_id')
    # ### end Alembic commands ###
