"""asdasd

Revision ID: 787b9ba5c7a4
Revises: 326095536168
Create Date: 2022-03-16 14:50:11.311845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787b9ba5c7a4'
down_revision = '326095536168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyal_card_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bonus_card_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loyal_card_payment')
    # ### end Alembic commands ###
