"""changes

Revision ID: 970aaf16a45f
Revises: 34dc4a2e1bee
Create Date: 2022-02-18 18:38:57.015732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970aaf16a45f'
down_revision = '34dc4a2e1bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'active')
    # ### end Alembic commands ###
