"""Asdd

Revision ID: aeca2a2706c2
Revises: e1574f16813e
Create Date: 2022-04-26 17:14:46.510538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeca2a2706c2'
down_revision = 'e1574f16813e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_counter_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('bill', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cashless', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('bonus', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('service', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_counter_daily')
    # ### end Alembic commands ###
