"""chenges

Revision ID: b2594023f09b
Revises: 6ef1fd61de46
Create Date: 2022-02-19 16:52:21.901224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2594023f09b'
down_revision = '6ef1fd61de46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('device_payment', sa.Column('device_code', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_payment', 'device_code')
    op.alter_column('device', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
