"""Sfdv

Revision ID: c654b0221fda
Revises: 50c58ed8d649
Create Date: 2022-04-23 14:59:26.311068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c654b0221fda'
down_revision = '50c58ed8d649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_payment', sa.Column('car_wash_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_payment', 'car_wash_id')
    # ### end Alembic commands ###
