"""Afvs

Revision ID: e1574f16813e
Revises: 
Create Date: 2022-04-25 13:46:16.749252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1574f16813e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_payment', sa.Column('device_code', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_payment', 'device_code')
    # ### end Alembic commands ###
